name: 更新检查器

env:
  FILE_NAME: MASTER
  REPO_BRANCH: master
  REPO_URL_LEDE: https://github.com/coolsnowwolf/lede

on:
  workflow_dispatch:
  schedule:
    - cron: 30 13 * * SUN

jobs:
  lede:
    runs-on: ubuntu-latest

    steps:

    - name: 获取提交哈希值
      id: getHash
      run: |
        git clone --depth 1 $REPO_URL_LEDE -b $REPO_BRANCH .
        echo "::set-output name=commitHash::$(git rev-parse HEAD)"
        
    - name: 比较提交哈希值
      id: cacheHash
      uses: actions/cache@v2
      with:
        path: .commitHash
        key: HEAD-${{ steps.getHash.outputs.commitHash }}

    - name: 保存新的哈希值
      if: steps.cacheHash.outputs.cache-hit != 'true'
      run: |
        echo ${{ steps.getHash.outputs.commitHash }} | tee .commitHash
        
    - name: 触发器生成编译
      if: steps.cacheHash.outputs.cache-hit != 'true'
      uses: peter-evans/repository-dispatch@v2
      with:
        token: ${{ secrets.ACTION_TOKEN }}
        event-type: lede Source Code Update

    - name: 源代码更新通知
      if: steps.cacheHash.outputs.cache-hit != 'true'
      run: |
        curl -k --data chat_id="${{ secrets.TELEGRAM_CHAT_ID }}" --data "text=${{ env.FILE_NAME }},lede源码更新了" "https://api.telegram.org/bot${{ secrets.TELEGRAM_BOT_TOKEN }}/sendMessage"
